code --install-extension dbaeumer.vscode-eslint 
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension HookyQR.beautify
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.Go
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension octref.vetur
code --install-extension PeterJausovec.vscode-docker
code --install-extension redhat.vscode-yaml
code --install-extension robertohuertasm.vscode-icons
code --install-extension shakram02.bash-beautify
code --install-extension xabikos.JavaScriptSnippets
code --install-extension haaaad.ansible